version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  web:
    depends_on:
      - "postgres"
      - "mailcatcher"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/magic-deck-builder
      - gems:/gems

  mailcatcher:
    image: zolweb/docker-mailcatcher:latest
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  postgres:
  gems: